modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
issueTrackerURL="http://github.com/strikerrocker/VanillaTweaks/issues/" #optional
license="MIT License"
[[mods]] #mandatory
modId="simplesweep" #mandatory
version="1.16.5_1.0" #mandatory
displayName="Simple Sweep" #mandatory
credits="Big shoutout to computers, without you I would have no job." #optional
authors="djmanly" #optional
description='''Simple Minecraft mod that removes the sweep attack unless the weapon is enchanted with a sweeping enchantment (i.e. Sweeping Edge).'''
[[dependencies.simplesweep]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplesweep]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplesweep]]
    modId="jei"
    mandatory=false
    versionRange="[7.6,)"
    ordering="NONE"
    side="BOTH"