modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
issueTrackerURL="http://github.com/strikerrocker/VanillaTweaks/issues/" #optional
[[mods]] #mandatory
modId="simplesweep" #mandatory
version="1.15.2_1.1" #mandatory
displayName="Simple Sweep" #mandatory
credits="Big shoutout to computers, without you I would have no job." #optional
authors="djmanly" #optional
description='''Simple Minecraft mod that removes the sweep attack unless the weapon is enchanted with a sweeping enchantment (i.e. Sweeping Edge).'''
[[dependencies.simplesweep]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplesweep]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplesweep]]
    modId="jei"
    mandatory=false
    versionRange="[6,)"
    ordering="NONE"
    side="BOTH"