modLoader="javafml" #mandatory
loaderVersion="${forge_version}" #mandatory
issueTrackerURL="http://github.com/strikerrocker/VanillaTweaks/issues/" #optional
license="MIT License"
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${version}" #mandatory
displayName="${mod_name}" #mandatory
credits="Big shoutout to computers, without you I would have no job." #optional
authors="${mod_author}" #optional
description='Removes the sweep attack unless the weapon is enchanted with a sweeping enchantment (i.e. Sweeping Edge).'
[[dependencies.simplesweep]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplesweep]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version}"
    ordering="NONE"
    side="BOTH"
