modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory
issueTrackerURL="http://github.com/strikerrocker/VanillaTweaks/issues/" #optional
license="MIT License"
[[mods]] #mandatory
modId="simplesweep" #mandatory
version="1.18.1_1.0" #mandatory
displayName="Simple Sweep" #mandatory
credits="Big shoutout to computers, without you I would have no job." #optional
authors="JDill" #optional
description='''Removes the sweep attack unless the weapon is enchanted with a sweeping enchantment (i.e. Sweeping Edge).'''
[[dependencies.simplesweep]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplesweep]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplesweep]]
    modId="jei"
    mandatory=false
    versionRange="[9,)"
    ordering="NONE"
    side="BOTH"